### ISSUE TITLE
geoPoint component saying `google is not defined`

### ISSUE THREAD

**Issue by johhansantana** [Canner/canner-firestore-cms#2]
```
<geoPoint keyName="place" />
```

Gets me an error saying:
```
Uncaught ReferenceError: google is not defined
```

**Comment by abz53378** [comment]
Hi, Johhan, please add the script of [google places API](https://developers.google.com/maps/documentation/javascript/places#GetStarted), thanks!

**Comment by faizanabidnaqvi** [comment]
Hi there!

I really love the project but when I try to use <geoPoint keyName="place/>, I get this error:
Error: Please report the error to dev team

I am not very experienced with this but I read this issue and tried adding the api script in header in the index.html script like this:
<script async defer src="https://maps.googleapis.com/maps/api/js?key=[myapikey]&callback=initMap"
    type="text/javascript"></script>

It still doesn't work. Any idea on why it might not be working?

**Comment by faizanabidnaqvi** [comment]
Actually, I am sorry, I added the wrong script. It was supposed to be:
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&libraries=places"></script>

Now I can see the map but it is all grey and the field is disabled.
![canner-geopoint](https://user-images.githubusercontent.com/5749036/55590176-be25b880-5764-11e9-8d13-6798865104aa.png)
