### ISSUE TITLE
render key in uiParams giving error when using a local function

### ISSUE THREAD

**Issue by johhansantana** [Canner/canner-firestore-cms#3]
If I do 
```javascript
import { renderUrl } from "./utils/columns";
```

and use it as
```
render: renderUrl
```

It works

but If I copy and paste the `renderUrl` function to the same file:

```javascript
function renderUrl(text) {
  if (text) {
    return <a href={`https://${text}`}>https://{text}</a>;
  } else {
    return "-";
  }
}
```
It gives me an error:
```
Error: unsupported type 'a'
```

**Comment by abz53378** [comment]
Hi, Johhan, we are using [babel-plugin-transform-react-jsx](https://babeljs.io/docs/en/babel-plugin-transform-react-jsx) to transform the `jsx` language, so in your `*.schema.js`, all `<tagName>` will be transform to `CannerScript('tagName', null)`.

If you want to write the `renderUrl` in the schema.js, the only way is not using the `jsx`, for example:


**index.schema.js**
```js
import React from 'react';
import CannerScript from 'canner-script'; // the pragma of `babel-plugin-transform-react-jsx` in *.schema.js

function renderUrl(text) {
  if (text) {
    const url = `https://${text}`;
    return React.createElement('a', {href: url}, url);
  } else {
    return '-';
  }
}
```

Thanks!
